okta:
  oauth2:
    issuer: https://dev-91414795.okta.com/oauth2/default
    client-id: {client-id}
    client-secret: {client-secert}
    redirect-uri: /authorization-code/callback

server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {client-id}
            client-secret:  {client-secert}